name: foss_warn
description: Eine FOSS Umsetzung von NINA
publish_to: 'none'
version: 0.8.0+32

environment:
  sdk: ">=2.17.0 <3.13.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  flutter_local_notifications: ^17.2.4
  shared_preferences: ^2.3.3
  shared_preferences_android: ^2.3.3
  provider: ^6.1.1
  rxdart: ^0.28.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.1
  android_alarm_manager_plus: ^4.0.4
  intl: any # for localizations
  unifiedpush: ^5.0.2
  xml2json: ^6.2.5

  # used by the map
  flutter_map: ^7.0.2
  flutter_map_geojson: ^1.0.5
  vector_map_tiles: ^8.0.0
  latlong2: ^0.9.0

  #icons_launcher: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/app_icon/app_icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/app_icon/app_icon.png"
      adaptive_background_color: '#cfe5ff'
      adaptive_foreground_image: "assets/app_icon/adaptive_icon.png"
      adaptive_monochrome_image: "assets/app_icon/adaptive_monochrome_app_icon.png"

flutter:
  generate: true # for localizations
  uses-material-design: true
  assets:
   # welcome screen
   - assets/app_icon/app_icon.png
   - assets/location.png
   - assets/battery.png
   - assets/check.png
   - assets/steps.png
   - assets/paragraph.png
